### ISSUE TITLE
Disappearing highlighting of keys when pausing 

### ISSUE THREAD

**Issue by lastant** [PolyMeilex/Neothesia#47]
When pausing while notes are being played, the highlighting of keys disappears.

**Comment by jeaye** [comment]
Hey! I'm jumping in here to say the same thing. I've been trying to use Neothesia to learn a tune slowly and I keep pausing when a chord is played, but the the notes currently being played get cleared until I play and the next note is played.

To be clear, I'm not using the play-along feature. Just viewing a midi file.

If Neothesia could keep the keys highlighting throughout the whole duration, including while paused, it would make learning these chords much simpler. :)

Thanks so much for this software.

**Comment by PolyMeilex** [comment]
Should be fixed in latest dev build:
[ubuntu-artifact(1).zip](https://github.com/PolyMeilex/Neothesia/files/12676540/ubuntu-artifact.1.zip)
[macos-artifact(1).zip](https://github.com/PolyMeilex/Neothesia/files/12676541/macos-artifact.1.zip)
[windows-artifact(1).zip](https://github.com/PolyMeilex/Neothesia/files/12676543/windows-artifact.1.zip)

**Comment by jeaye** [comment]
Perfect! I just checked and it's looking good on my end. Thanks so much. :)
